# Generated by Django 4.0 on 2022-01-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('voucher_id', models.CharField(choices=[('PP', '紙本'), ('CC', '信用卡'), ('ET', '電子票券'), ('MB', '行動支付')], default='PP', max_length=2)),
            ],
            options={
                'ordering': ['-ssn'],
            },
        ),
    ]
